addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      # odoo-argentina fe
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2

language: python

# new options suggested by Alexandre Fayolle
# we need sudo for apt-get install
# sudo: false
cache: pip

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: znz/SSupt0Srn+J1SF2V4nRYEGlx3nOh6BscNth0iv5VNdLoGxMreOfZJ4GVtv9N7rPb/469ApBtV/L+mHJyumd18f8BAszsjkMSjWst5MnfuijX0emm2i1gHZOP9lHKKCv3fN5bCubizBN6+cwQ84+kCeqzf6v9qDOVjByRpI3n8N+iYU5yBhh7VjzhVGWj761j5vMUJI72jT0iFRwVnebfefKh9w8gYPyKgddW4cqNPChNXkiWSZAw7qBvU2ElMI6gGZCBFOoKBj2Gy6mcXap5ZDssPRZsnH11sop9wYZ573Rf1UFZNlc9IQUaDnagojaGjWEnIFjVO4uxZJpAgDBz7MIYT7nYWbsBu2q3bYWGJ9I3tozSyJ/lXkLm9q6nVQ5o8LI6BzFQkPukupVExIVQ285Ag/cc28gxCX7L8ANfKUyfzUszaqXaeTS4klLQERaBY1CdCbheNGDpXAFKq2avukCdGzJ99NTaIFKCCM5RP1wE/AysrkHZSArUmGm+ABRNQJ4LsDdOPHwb+1QTaXjiPRpYFPDb35vb0mF3dPSAUG4zd9BsjZzy8EAdfg8EMx6YzuZWHi3wPzbWDuNBc/ErfVSJBLcJHAGol7loMUVT+307xh8P64xU1D0f+BuzoI7JdM0Nj99uaiSjsgIyDMFBiL01I1BNweqmt7AKNuM=

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  # TODO fix error and include this modules
  - TRANSIFEX="1" EXCLUDE="partner_state,product_internal_code,partner_internal_code,product_variant_imp"
  # TODO fix and include this modules:
    # we exclude partner_state because it gives an error and we could not find why
    # we also exclude partner and product internal code and product_variant_imp because they gives an error with website sale tests. We make unit tests for them
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="partner_state,product_internal_code,partner_internal_code,product_variant_imp"
  - UNIT_TEST="1" INCLUDE="partner_state,product_internal_code,partner_internal_code,product_variant_imp"
  # TODO enable unit_test to all modules to test dependencies (takes to long for now)
  # - UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  # we install libcups2-dev here because it is not on travis whitelist so it is not installable by addons/apt/packages
  # you can check if available on https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcups2-dev
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo argentina (TODO try to remove dependency, only interest module and move invoice)
  - git clone https://github.com/ingadhoc/odoo-argentina.git ${HOME}/odoo-argentina
  - pip install geopy==0.95.1 BeautifulSoup 

  # for product_cost_currency
  - git clone https://github.com/OCA/margin-analysis.git ${HOME}/margin-analysis

  # odoo argentina fe
  - pip install pyOpenSSL suds httplib2 pysimplesoap==1.08.8 m2crypto fpdf dbf Pillow
  # install pyafipws after others dependencies because dependency erro
  - pip install pyafipws

  # for odoo pdf reports (tested on sale for eg.)
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
